/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author f.gysel
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        filmMachenButton = new javax.swing.JButton();
        movieName = new javax.swing.JTextField();
        movieDate = new javax.swing.JTextField();
        movieDauer = new javax.swing.JTextField();
        movieSaal = new javax.swing.JComboBox();
        aendereReservierungButton = new javax.swing.JButton();
        machReservierungButton = new javax.swing.JButton();
        storniereReservierungButton = new javax.swing.JButton();
        kaufPlatzButton = new javax.swing.JButton();
        liefereBuchungNummerButton = new javax.swing.JButton();
        checkPlaetzeButton = new javax.swing.JButton();
        zeigeAlleVorstellungButton = new javax.swing.JButton();
        buyPlaceTakePlatz = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filmMachenButton.setText("neuen Film erstellen");
        filmMachenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmMachenButtonActionPerformed(evt);
            }
        });

        movieName.setText("Name");

        movieDate.setText("Datum");

        movieDauer.setText("Dauer");

        movieSaal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        movieSaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieSaalActionPerformed(evt);
            }
        });

        aendereReservierungButton.setText("Reservierung ändern");
        aendereReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aendereReservierungButtonActionPerformed(evt);
            }
        });

        machReservierungButton.setText("Reservierung erstellen");
        machReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machReservierungButtonActionPerformed(evt);
            }
        });

        storniereReservierungButton.setText("Reservierung löschen");

        kaufPlatzButton.setText("Platz kaufen");
        kaufPlatzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaufPlatzButtonActionPerformed(evt);
            }
        });

        liefereBuchungNummerButton.setText("Buchungsnummern checken");
        liefereBuchungNummerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liefereBuchungNummerButtonActionPerformed(evt);
            }
        });

        checkPlaetzeButton.setText("Plätze checken");
        checkPlaetzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPlaetzeButtonActionPerformed(evt);
            }
        });

        zeigeAlleVorstellungButton.setText("Zeige alle Filme");
        zeigeAlleVorstellungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeigeAlleVorstellungButtonActionPerformed(evt);
            }
        });

        buyPlaceTakePlatz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        buyPlaceTakePlatz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPlaceTakePlatzActionPerformed(evt);
            }
        });

        jLabel3.setText("Platz: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyPlaceTakePlatz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storniereReservierungButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(aendereReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(machReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(liefereBuchungNummerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaufPlatzButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(machReservierungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aendereReservierungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storniereReservierungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liefereBuchungNummerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaufPlatzButton)
                    .addComponent(buyPlaceTakePlatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filmMachenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmMachenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmMachenButtonActionPerformed

    private void movieSaalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieSaalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieSaalActionPerformed

    private void kaufPlatzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaufPlatzButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaufPlatzButtonActionPerformed

    private void machReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machReservierungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machReservierungButtonActionPerformed

    private void aendereReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aendereReservierungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aendereReservierungButtonActionPerformed

    private void liefereBuchungNummerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liefereBuchungNummerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liefereBuchungNummerButtonActionPerformed

    private void checkPlaetzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPlaetzeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPlaetzeButtonActionPerformed

    private void zeigeAlleVorstellungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeigeAlleVorstellungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeigeAlleVorstellungButtonActionPerformed

    private void buyPlaceTakePlatzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPlaceTakePlatzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyPlaceTakePlatzActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aendereReservierungButton;
    private javax.swing.JComboBox buyPlaceTakePlatz;
    private javax.swing.JButton checkPlaetzeButton;
    private javax.swing.JButton filmMachenButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton kaufPlatzButton;
    private javax.swing.JButton liefereBuchungNummerButton;
    private javax.swing.JButton machReservierungButton;
    private javax.swing.JTextField movieDate;
    private javax.swing.JTextField movieDauer;
    private javax.swing.JTextField movieName;
    private javax.swing.JComboBox movieSaal;
    private javax.swing.JButton storniereReservierungButton;
    private javax.swing.JButton zeigeAlleVorstellungButton;
    // End of variables declaration//GEN-END:variables
}
