/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author f.gysel
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        filmMachenButton = new javax.swing.JButton();
        movieName = new javax.swing.JTextField();
        movieDate = new javax.swing.JTextField();
        movieDauer = new javax.swing.JTextField();
        movieSaal = new javax.swing.JComboBox();
        aendereReservierungButton = new javax.swing.JButton();
        machReservierungButton = new javax.swing.JButton();
        storniereReservierungButton = new javax.swing.JButton();
        kaufPlatzButton = new javax.swing.JButton();
        checkPlaetzeButton = new javax.swing.JButton();
        zeigeAlleVorstellungButton = new javax.swing.JButton();
        buyPlaceTakePlatz = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        telefonNummerField = new javax.swing.JTextField();
        reservierPlaceTakePlatz = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        changeReservierungOldPlace = new javax.swing.JComboBox();
        changeReservierungNewPlace = new javax.swing.JComboBox();
        deleteReservierungTakeNumber = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filmMachenButton.setText("neuen Film erstellen");
        filmMachenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmMachenButtonActionPerformed(evt);
            }
        });

        movieName.setText("Name");

        movieDate.setText("Datum");

        movieDauer.setText("Zeit");

        movieSaal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        movieSaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieSaalActionPerformed(evt);
            }
        });

        aendereReservierungButton.setText("Reservierung ändern");
        aendereReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aendereReservierungButtonActionPerformed(evt);
            }
        });

        machReservierungButton.setText("Reservierung erstellen");
        machReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machReservierungButtonActionPerformed(evt);
            }
        });

        storniereReservierungButton.setText("Reservierung löschen");
        storniereReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storniereReservierungButtonActionPerformed(evt);
            }
        });

        kaufPlatzButton.setText("Platz kaufen");
        kaufPlatzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaufPlatzButtonActionPerformed(evt);
            }
        });

        checkPlaetzeButton.setText("Plätze checken");
        checkPlaetzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPlaetzeButtonActionPerformed(evt);
            }
        });

        zeigeAlleVorstellungButton.setText("Zeige alle Filme");
        zeigeAlleVorstellungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeigeAlleVorstellungButtonActionPerformed(evt);
            }
        });

        buyPlaceTakePlatz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        buyPlaceTakePlatz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPlaceTakePlatzActionPerformed(evt);
            }
        });

        jLabel3.setText("Platz: ");

        telefonNummerField.setText("Telefonnummer");
        telefonNummerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonNummerFieldActionPerformed(evt);
            }
        });

        reservierPlaceTakePlatz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        reservierPlaceTakePlatz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservierPlaceTakePlatzActionPerformed(evt);
            }
        });

        jLabel5.setText("Platz: ");

        changeReservierungOldPlace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        changeReservierungOldPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeReservierungOldPlaceActionPerformed(evt);
            }
        });

        changeReservierungNewPlace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        changeReservierungNewPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeReservierungNewPlaceActionPerformed(evt);
            }
        });

        deleteReservierungTakeNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        deleteReservierungTakeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReservierungTakeNumberActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefonnummer:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Kinobuchungssystem Modul 326");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buyPlaceTakePlatz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefonNummerField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(changeReservierungOldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservierPlaceTakePlatz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeReservierungNewPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteReservierungTakeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storniereReservierungButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aendereReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(machReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaufPlatzButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machReservierungButton)
                    .addComponent(telefonNummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservierPlaceTakePlatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aendereReservierungButton)
                    .addComponent(changeReservierungOldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeReservierungNewPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storniereReservierungButton)
                    .addComponent(deleteReservierungTakeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaufPlatzButton)
                    .addComponent(buyPlaceTakePlatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filmMachenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmMachenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmMachenButtonActionPerformed

    private void movieSaalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieSaalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieSaalActionPerformed

    private void kaufPlatzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaufPlatzButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaufPlatzButtonActionPerformed

    private void machReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machReservierungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machReservierungButtonActionPerformed

    private void aendereReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aendereReservierungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aendereReservierungButtonActionPerformed

    private void checkPlaetzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPlaetzeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPlaetzeButtonActionPerformed

    private void zeigeAlleVorstellungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeigeAlleVorstellungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeigeAlleVorstellungButtonActionPerformed

    private void buyPlaceTakePlatzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPlaceTakePlatzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyPlaceTakePlatzActionPerformed

    private void telefonNummerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonNummerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonNummerFieldActionPerformed

    private void reservierPlaceTakePlatzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservierPlaceTakePlatzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservierPlaceTakePlatzActionPerformed

    private void changeReservierungOldPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeReservierungOldPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeReservierungOldPlaceActionPerformed

    private void changeReservierungNewPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeReservierungNewPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeReservierungNewPlaceActionPerformed

    private void deleteReservierungTakeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReservierungTakeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteReservierungTakeNumberActionPerformed

    private void storniereReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storniereReservierungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storniereReservierungButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aendereReservierungButton;
    private javax.swing.JComboBox buyPlaceTakePlatz;
    private javax.swing.JComboBox changeReservierungNewPlace;
    private javax.swing.JComboBox changeReservierungOldPlace;
    private javax.swing.JButton checkPlaetzeButton;
    private javax.swing.JComboBox deleteReservierungTakeNumber;
    private javax.swing.JButton filmMachenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton kaufPlatzButton;
    private javax.swing.JButton machReservierungButton;
    private javax.swing.JTextField movieDate;
    private javax.swing.JTextField movieDauer;
    private javax.swing.JTextField movieName;
    private javax.swing.JComboBox movieSaal;
    private javax.swing.JComboBox reservierPlaceTakePlatz;
    private javax.swing.JButton storniereReservierungButton;
    private javax.swing.JTextField telefonNummerField;
    private javax.swing.JButton zeigeAlleVorstellungButton;
    // End of variables declaration//GEN-END:variables
}
