package modul326.kinobuchungssystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author f.gysel
 */
public class gui extends javax.swing.JFrame {

    Kinobuchungssystem k;

    /**
     * Creates new form NewJFrame
     *
     * @param k 
     */
    public gui(Kinobuchungssystem k) {
        this.k = k;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        filmMachenButton = new javax.swing.JButton();
        movieName = new javax.swing.JTextField();
        movieDate = new javax.swing.JTextField();
        movieDauer = new javax.swing.JTextField();
        movieSaal = new javax.swing.JComboBox();
        aendereReservierungButton = new javax.swing.JButton();
        machReservierungButton = new javax.swing.JButton();
        storniereReservierungButton = new javax.swing.JButton();
        kaufPlatzButton = new javax.swing.JButton();
        checkPlaetzeButton = new javax.swing.JButton();
        zeigeAlleVorstellungButton = new javax.swing.JButton();
        buyPlaceTakePlatz = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filmMachenButton.setText("neuen Film erstellen");
        filmMachenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmMachenButtonActionPerformed(evt);
            }
        });

        movieName.setText("Name");

        movieDate.setText("Datum");

        movieDauer.setText("Dauer");

        movieSaal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        movieSaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieSaalActionPerformed(evt);
            }
        });

        aendereReservierungButton.setText("Reservierung ändern");
        aendereReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aendereReservierungButtonActionPerformed(evt);
            }
        });

        machReservierungButton.setText("Reservierung erstellen");
        machReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machReservierungButtonActionPerformed(evt);
            }
        });

        storniereReservierungButton.setText("Reservierung löschen");

        kaufPlatzButton.setText("Platz kaufen");
        kaufPlatzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaufPlatzButtonActionPerformed(evt);
            }
        });

        checkPlaetzeButton.setText("Plätze checken");
        checkPlaetzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPlaetzeButtonActionPerformed(evt);
            }
        });

        zeigeAlleVorstellungButton.setText("Zeige alle Filme");
        zeigeAlleVorstellungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeigeAlleVorstellungButtonActionPerformed(evt);
            }
        });

        buyPlaceTakePlatz.setModel(new javax.swing.DefaultComboBoxModel(k.getPlaetzeASarray()));
        buyPlaceTakePlatz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPlaceTakePlatzActionPerformed(evt);
            }
        });

        jLabel3.setText("Platz: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyPlaceTakePlatz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storniereReservierungButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(aendereReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(machReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaufPlatzButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(machReservierungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aendereReservierungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storniereReservierungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaufPlatzButton)
                    .addComponent(buyPlaceTakePlatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>            

    private void filmMachenButtonActionPerformed(java.awt.event.ActionEvent evt) {
        k.filmMachen(movieName.getText(), movieDate.getText(), movieDauer.getText(), k.saele.get(0));
        System.err.println("Film hinzugefügt!");
    }

    private void checkPlaetzeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        k.checkPlaetze();
    }

    private void movieSaalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kaufPlatzButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String workWith = (String) buyPlaceTakePlatz.getSelectedItem();
        
        String[] parts = workWith.split("  |   ");
        String[] saalNr = parts[0].split("Saal ");
        int saalNummer = Integer.parseInt(saalNr[1]);
        String[] reiheNr = parts[2].split("Reihe ");
        int reiheNummer = Integer.parseInt(reiheNr[1]);
        String[] platzNr = parts[4].split("Platz ");
        int platzNummer = Integer.parseInt(platzNr[1]);
        //reiheNummer = reiheNummer - ((reiheNummer / reiheNummer % saalNummer) * 4);
        //platzNummer = platzNummer - ((platzNummer / platzNummer % reiheNummer) * 4);
//        System.out.println(saalNummer);
//        System.out.println(reiheNummer);
//        System.out.println(platzNummer);
        System.out.println(platzNummer);
        //k.kaufPlatz(k.saele.get(saalNummer).reihe.get(reiheNummer).platz.get(platzNummer));
        k.kaufPlatz(k.saele.get(0).reihe.get(0).platz.get(platzNummer - 1));
        
    }

    private void machReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {
        k.machReservierung(WIDTH, null, null);
    }

    private void aendereReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void zeigeAlleVorstellungButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        k.zeigeAlleVorstellung();
    } 
    
    
    private void buyPlaceTakeReiheActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void buyPlaceTakeSaalActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void buyPlaceTakePlatzActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }           

    
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton aendereReservierungButton;
    private javax.swing.JComboBox buyPlaceTakePlatz;
    private javax.swing.JComboBox buyPlaceTakeReihe;
    private javax.swing.JComboBox buyPlaceTakeSaal;
    private javax.swing.JButton checkPlaetzeButton;
    private javax.swing.JButton filmMachenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton kaufPlatzButton;
    private javax.swing.JButton machReservierungButton;
    private javax.swing.JTextField movieDate;
    private javax.swing.JTextField movieDauer;
    private javax.swing.JTextField movieName;
    private javax.swing.JComboBox movieSaal;
    private javax.swing.JButton storniereReservierungButton;
    private javax.swing.JButton zeigeAlleVorstellungButton;
    // End of variables declaration     
}
// k.getPlaetzeASarray()