package modul326.kinobuchungssystem;

import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author f.gysel
 */
public class gui extends javax.swing.JFrame {

    Kinobuchungssystem k;

    /**
     * Creates new form NewJFrame
     *
     * @param k
     */
    public gui(Kinobuchungssystem k) {
        this.k = k;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        filmMachenButton = new javax.swing.JButton();
        movieName = new javax.swing.JTextField();
        movieDate = new javax.swing.JTextField();
        movieDauer = new javax.swing.JTextField();
        movieSaal = new javax.swing.JComboBox();
        aendereReservierungButton = new javax.swing.JButton();
        machReservierungButton = new javax.swing.JButton();
        storniereReservierungButton = new javax.swing.JButton();
        kaufPlatzButton = new javax.swing.JButton();
        checkPlaetzeButton = new javax.swing.JButton();
        zeigeAlleVorstellungButton = new javax.swing.JButton();
        buyPlaceTakePlatz = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        telefonNummerField = new javax.swing.JTextField();
        reservierPlaceTakePlatz = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        changeReservierungOldPlace = new javax.swing.JComboBox();
        changeReservierungNewPlace = new javax.swing.JComboBox();
        deleteReservierungTakeNumber = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filmMachenButton.setText("neuen Film erstellen");
        filmMachenButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmMachenButtonActionPerformed(evt);
            }
        });

        movieName.setText("Name");

        movieDate.setText("Datum");

        movieDauer.setText("Zeit");

        movieSaal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        movieSaal.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieSaalActionPerformed(evt);
            }
        });

        aendereReservierungButton.setText("Reservierung ändern");
        aendereReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aendereReservierungButtonActionPerformed(evt);
            }
        });

        machReservierungButton.setText("Reservierung erstellen");
        machReservierungButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machReservierungButtonActionPerformed(evt);
            }
        });

        storniereReservierungButton.setText("Reservierung löschen");

        kaufPlatzButton.setText("Platz kaufen");
        kaufPlatzButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaufPlatzButtonActionPerformed(evt);
            }
        });

        checkPlaetzeButton.setText("Plätze checken");
        checkPlaetzeButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPlaetzeButtonActionPerformed(evt);
            }
        });

        zeigeAlleVorstellungButton.setText("Zeige alle Filme");
        zeigeAlleVorstellungButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeigeAlleVorstellungButtonActionPerformed(evt);
            }
        });

        buyPlaceTakePlatz.setModel(new javax.swing.DefaultComboBoxModel(k.getPlaetzeASarray()));
        buyPlaceTakePlatz.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPlaceTakePlatzActionPerformed(evt);
            }
        });

        jLabel3.setText("Platz: ");

        telefonNummerField.setText("Telefonnummer");
        telefonNummerField.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonNummerFieldActionPerformed(evt);
            }
        });

        reservierPlaceTakePlatz.setModel(new javax.swing.DefaultComboBoxModel(k.getPlaetzeASarray()));
        reservierPlaceTakePlatz.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservierPlaceTakePlatzActionPerformed(evt);
            }
        });

        jLabel5.setText("Platz: ");

        changeReservierungOldPlace.setModel(new javax.swing.DefaultComboBoxModel(k.getPlaetzeASarray()));
        changeReservierungOldPlace.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeReservierungOldPlaceActionPerformed(evt);
            }
        });

        changeReservierungNewPlace.setModel(new javax.swing.DefaultComboBoxModel(k.getPlaetzeASarray()));
        changeReservierungNewPlace.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeReservierungNewPlaceActionPerformed(evt);
            }
        });

        deleteReservierungTakeNumber.setModel(new javax.swing.DefaultComboBoxModel(k.getReservierungenASarray()));
        deleteReservierungTakeNumber.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReservierungTakeNumberActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefonnummer:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Kinobuchungssystem Modul 326");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buyPlaceTakePlatz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefonNummerField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(changeReservierungOldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservierPlaceTakePlatz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeReservierungNewPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteReservierungTakeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storniereReservierungButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aendereReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(machReservierungButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaufPlatzButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkPlaetzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zeigeAlleVorstellungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmMachenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieSaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDauer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machReservierungButton)
                    .addComponent(telefonNummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservierPlaceTakePlatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aendereReservierungButton)
                    .addComponent(changeReservierungOldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeReservierungNewPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storniereReservierungButton)
                    .addComponent(deleteReservierungTakeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaufPlatzButton)
                    .addComponent(buyPlaceTakePlatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>           

    private void filmMachenButtonActionPerformed(java.awt.event.ActionEvent evt) {
        k.filmMachen(movieName.getText(), movieDate.getText(), movieDauer.getText(), k.saele.get(0));
        System.err.println("Film hinzugefügt!");
    }

    private void checkPlaetzeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        k.checkPlaetze();
    }

    private void movieSaalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kaufPlatzButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String workWith = (String) buyPlaceTakePlatz.getSelectedItem();
        int get = getSelectedPlace(workWith);
       // k.kaufPlatz(k.saele.get(0).reihe.get(0).platz.get(getSelectedPlace(workWith) - 1));
    }

    private int getSelectedPlace(String workWith) {
        
        
        
        String[] parts = workWith.split("-");
        int platzNr = Integer.parseInt(parts[1]);
        
        
        
        int longPlatz = platzNr;
        
        int longReihe = Math.round((longPlatz - 1) / 4);
        
        int longSaal = Math.round(longReihe / 4);
        
        int kurzReihe = longReihe - (longSaal * 4);
        
        int kurzPlatz = longPlatz - (longReihe * 4); 
        
        System.out.println(longPlatz);
        System.out.println(longReihe);
        System.out.println(longSaal);
        System.out.println(kurzPlatz);
        System.out.println(kurzReihe);
        
        
        return platzNr;
    }

    private void machReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String workWith = (String) reservierPlaceTakePlatz.getSelectedItem();
        k.machReservierung(telefonNummerField.getText(), k.saele.get(0).reihe.get(0).platz.get(getSelectedPlace(workWith) - 1));
    }

    private void telefonNummerFieldActionPerformed(ActionEvent evt) {

    }

    private void aendereReservierungButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void zeigeAlleVorstellungButtonActionPerformed(java.awt.event.ActionEvent evt) {
        k.zeigeAlleVorstellung();
    }

    private void buyPlaceTakeReiheActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buyPlaceTakeSaalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buyPlaceTakePlatzActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void reservierPlaceTakePlatzActionPerformed(ActionEvent evt) {

    }

        private void changeReservierungOldPlaceActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void changeReservierungNewPlaceActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void deleteReservierungTakeNumberActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }         
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton aendereReservierungButton;
    private javax.swing.JComboBox buyPlaceTakePlatz;
    private javax.swing.JComboBox changeReservierungNewPlace;
    private javax.swing.JComboBox changeReservierungOldPlace;
    private javax.swing.JButton checkPlaetzeButton;
    private javax.swing.JComboBox deleteReservierungTakeNumber;
    private javax.swing.JButton filmMachenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton kaufPlatzButton;
    private javax.swing.JButton machReservierungButton;
    private javax.swing.JTextField movieDate;
    private javax.swing.JTextField movieDauer;
    private javax.swing.JTextField movieName;
    private javax.swing.JComboBox movieSaal;
    private javax.swing.JComboBox reservierPlaceTakePlatz;
    private javax.swing.JButton storniereReservierungButton;
    private javax.swing.JTextField telefonNummerField;
    private javax.swing.JButton zeigeAlleVorstellungButton;
    // End of variables declaration         
}
// k.getPlaetzeASarray()
